- name: "Single Page Websites"
  description: Get your business online quickly and easily with one of our single page websites.  Perfect for small businesses and sole traders.
  tease-line: Beautiful websites, made simple.
  background-image: /assets/images/single_page_websites.jpg
  icon-image: /assets/images/single_page_websites_icon.png
  url: /websites/single-page-websites
  benefits:
  - name: "Responsive Web Design"
    description: From small mobile devices to tablets and larger desktop computers, Scroll If's websites are built and optimised to display all content in a responsive and predictable manner.
    icon-image: /assets/images/checkmark_temp.png
  - name: "Browser Compatability"
    description: Implementation of cross browser testing and careful coding practices ensure your website will function as intended across the variety of popular browsers and operating systems.
    icon-image: /assets/images/checkmark_temp.png
  - name: "Hosting Services"
    description: Take advantage of Scroll If's included web hosting options to get your website live on the internet. Link a Domain Name you have purchased to your website or simply have it published under a generic URL at no extra cost.
    icon-image: /assets/images/checkmark_temp.png
  - name: "Unique Look & Feel"
    description: Scroll If can encorporate your ideas into the design process of your website to give you the website of your dreams, or start completely from scratch and build it from the ground up.
    icon-image: /assets/images/checkmark_temp.png
  - name: "SEO & Analytics"
    description: Get monthly reports derived using Google Analytics to understand more about the visitors to your website. Scroll If's coding utilises organic SEO to help increase your website's online presence.
    icon-image: /assets/images/checkmark_temp.png
  - name: ""
    description: 
    icon-image: 
- name: "Multi Page Websites"
  description: Make a mark on the web with one of our multi page websites.  Suited to larger businesses that need to display a lot of content.
  tease-line: Business websites, supercharged.
  background-image: /assets/images/multi_page_websites.jpg
  icon-image: /assets/images/multi_page_websites_icon.png
  url: /websites/multi-page-websites
- name: "Business Logos"
  description: Help your business stand out amongst the crowd with a custom business logo.
  tease-line: Stand out, be remembered.
  background-image: /assets/images/business_logos.jpg
  icon-image: /assets/images/business_logos_icon.png
  url: /graphics/business-logos
- name: "Social Media Banners"
  description: Let your business look its best everywhere with matching social media banners.
  tease-line: Look your best, be your best.
  background-image: /assets/images/social_media_banners.jpg
  icon-image: /assets/images/social_media_banners_icon.png
  url: /graphics/social-media-banners
- name: "Business Cards"
  description: Give your business that professional touch with a memorable business card.
  tease-line: Your business, in a pocket.
  background-image: /assets/images/business_cards.jpg
  icon-image: /assets/images/business_cards_icon.png
  url: /graphics/business-cards
- name: "HTML Emails"
  description: Make your business communications pop with emails that match your business's style.
  tease-line: Business emails, made exciting.
  background-image: /assets/images/html_emails.jpg
  icon-image: /assets/images/html_emails_icon.png
  url: /graphics/html_emails
- name: "Consulting: Systems"
  description: Need to implement a new system? Let us guide the installation and rollout.
  tease-line: Business tools, established. 
  background-image: /assets/images/consulting_systems.jpg
  icon-image: /assets/images/consulting_systems_icon.png
  url: /consulting/systems
- name: "Consulting: Operations"
  description: Even the best teams and tools need equally great processes to succeed.
  tease-line: Business processes, solved.
  background-image: /assets/images/consulting_operations.jpg
  icon-image: /assets/images/consulting_operations_icon.png
  url: /consulting/operations
- name: "Consulting: Branding"
  description: Like a makeup team and costume designer for your business.  Make a memorable first impression to your customers.
  tease-line: Your business, dressed to impress.
  background-image: /assets/images/consulting_branding.jpg
  icon-image: /assets/images/consulting_branding_icon.png
  url: /consulting/branding