- name: "Single Page Websites"
  url: /websites/single-page-websites
  background-image: /assets/images/single_page_websites.jpg
  description: Get your business online quickly and easily with one of our single page websites.  Perfect for small businesses and sole traders.
  icon-image: /assets/images/single_page_websites_icon.png
  tease-line: Beautiful websites, made simple.
  shoutouts:
  - name: Empower your business to reach a broader audience.
  - name: Establish credibility with a strong online presence.
  explanations:
  - name: Single page websites are perfect for small businesses that want to make a large statement!
  - name: Avoid visitors to your website getting lost in multiple layers of navigation or stuck in an endless search for what they need.
  - name: Single page websites naturally guide visitors through your content smoothly, and gives you control over the story you tell as they browse your site.
  impact-image: /assets/images/digital_solutions_agency.jpg
  quote: Websites can provide as much impact to a business as a storefront.
  benefits:
  - name: Responsive Web Design
    description: From small mobile devices to tablets and larger desktop computers, Scroll If's websites are built and optimised to display all content in a responsive and predictable manner.
  - name: Browser Compatability
    description: Implementation of cross browser testing and careful coding practices ensure your website will function as intended across the variety of popular browsers and operating systems.
  - name: Hosting Services
    description: Take advantage of Scroll If's included web hosting options to get your website live on the internet. Link a Domain Name you have purchased to your website or simply have it published under a generic URL at no extra cost.
  - name: Unique Look & Feel
    description: Scroll If can encorporate your ideas into the design process of your website to give you the website of your dreams, or start completely from scratch and build it from the ground up.
  - name: SEO & Analytics
    description: Get monthly reports derived using Google Analytics to understand more about the visitors to your website. Scroll If's coding utilises organic SEO to help increase your website's online presence.
  - name: Ongoing Support
    description: Has something in your business changed that should be reflected on your website? Want to add something fresh to liven up your website? Scroll If takes care of the upkeep and changes to your site.
  prices:
  - name: Stand Alone Single Page Website
    description: Purchase one of our custom built website outright and manage the hosting and upkeep yourself.
    cost: from $945
    fine-print: * Final price may vary.
  how-it-works:
  - name: "1. Inspire"
    description: Start from scratch, improve an existing design, or have us create you a fresh masterpiece.
    background-image: /assets/images/single_page_websites.jpg
  - name: "2. Create"
    description: Let us turn your vision into a reality. Our development process puts pen to paper, and paper to screen.
    background-image: /assets/images/single_page_websites.jpg
  - name: "3. Align"
    description: A chance to make any last minute adjustments or additions to our creation and add the finishing touches.
    background-image: /assets/images/single_page_websites.jpg
  - name: "4. Launch"
    description: The most exciting part of the process, go live time!
    background-image: /assets/images/single_page_websites.jpg

- name: "Multi Page Websites"
  url: /websites/multi-page-websites
  background-image: /assets/images/multi_page_websites.jpg
  description: Make a mark on the web with one of our multi page websites.  Suited to larger businesses that need to display a lot of content.
  icon-image: /assets/images/multi_page_websites_icon.png
  tease-line: Business websites, supercharged.
  shoutouts:
  - name: ""
  - name: ""
  explanations:
  - name: ""
  - name: ""
  - name: ""
  impact-image: /assets/images/digital_solutions_agency.jpg
  quote: ""
  benefits:
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  how-it-works:
  - name: "1. Inspire"
    description: Start from scratch, improve an existing design, or have us create you a freash masterpiece.
    background-image: /assets/images/single_page_websites.jpg
  - name: "2. Create"
    description: Let us turn your vision into a reality. Our development process puts pen to paper, and paper to screen.
    background-image: /assets/images/single_page_websites.jpg
  - name: "3. Align"
    description: A chance to make any last minute adjustments or additions to our creation and add the finishing touches.
    background-image: /assets/images/single_page_websites.jpg
  - name: "4. Launch"
    description: The most exciting part of the process, go live time!
    background-image: /assets/images/single_page_websites.jpg

- name: "Business Logos"
  url: /graphics/business-logos
  background-image: /assets/images/business_logos.jpg
  description: Help your business stand out amongst the crowd with a custom business logo.
  icon-image: /assets/images/business_logos_icon.png
  tease-line: Stand out, be remembered.
  shoutouts:
  - name: ""
  - name: ""
  explanations:
  - name: ""
  - name: ""
  - name: ""
  impact-image: /assets/images/digital_solutions_agency.jpg
  quote: ""
  benefits:
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  how-it-works:
  - name: "1. Inspire"
    description: Start from scratch, improve an existing design, or have us create you a freash masterpiece.
    background-image: /assets/images/single_page_websites.jpg
  - name: "2. Create"
    description: Let us turn your vision into a reality. Our development process puts pen to paper, and paper to screen.
    background-image: /assets/images/single_page_websites.jpg
  - name: "3. Align"
    description: A chance to make any last minute adjustments or additions to our creation and add the finishing touches.
    background-image: /assets/images/single_page_websites.jpg
  - name: "4. Launch"
    description: The most exciting part of the process, go live time!
    background-image: /assets/images/single_page_websites.jpg

- name: "Social Media Banners"
  url: /graphics/social-media-banners
  background-image: /assets/images/social_media_banners.jpg
  description: Let your business look its best everywhere with matching social media banners.
  icon-image: /assets/images/social_media_banners_icon.png
  tease-line: Look your best, be your best.
  shoutouts:
  - name: ""
  - name: ""
  explanations:
  - name: ""
  - name: ""
  - name: ""
  impact-image: /assets/images/digital_solutions_agency.jpg
  quote: ""
  benefits:
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  how-it-works:
  - name: "1. Inspire"
    description: Start from scratch, improve an existing design, or have us create you a freash masterpiece.
    background-image: /assets/images/single_page_websites.jpg
  - name: "2. Create"
    description: Let us turn your vision into a reality. Our development process puts pen to paper, and paper to screen.
    background-image: /assets/images/single_page_websites.jpg
  - name: "3. Align"
    description: A chance to make any last minute adjustments or additions to our creation and add the finishing touches.
    background-image: /assets/images/single_page_websites.jpg
  - name: "4. Launch"
    description: The most exciting part of the process, go live time!
    background-image: /assets/images/single_page_websites.jpg

- name: "Business Cards"
  url: /graphics/business-cards
  background-image: /assets/images/business_cards.jpg
  description: Give your business that professional touch with a memorable business card.
  icon-image: /assets/images/business_cards_icon.png
  tease-line: Your business, in a pocket.
  shoutouts:
  - name: ""
  - name: ""
  explanations:
  - name: ""
  - name: ""
  - name: ""
  impact-image: /assets/images/digital_solutions_agency.jpg
  quote: ""
  benefits:
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  how-it-works:
  - name: "1. Inspire"
    description: Start from scratch, improve an existing design, or have us create you a freash masterpiece.
    background-image: /assets/images/single_page_websites.jpg
  - name: "2. Create"
    description: Let us turn your vision into a reality. Our development process puts pen to paper, and paper to screen.
    background-image: /assets/images/single_page_websites.jpg
  - name: "3. Align"
    description: A chance to make any last minute adjustments or additions to our creation and add the finishing touches.
    background-image: /assets/images/single_page_websites.jpg
  - name: "4. Launch"
    description: The most exciting part of the process, go live time!
    background-image: /assets/images/single_page_websites.jpg

- name: "HTML Emails"
  url: /graphics/html_emails
  background-image: /assets/images/html_emails.jpg
  description: Make your business communications pop with emails that match your business's style.
  icon-image: /assets/images/html_emails_icon.png
  tease-line: Business emails, made exciting.
  shoutouts:
  - name: ""
  - name: ""
  explanations:
  - name: ""
  - name: ""
  - name: ""
  impact-image: /assets/images/digital_solutions_agency.jpg
  quote: ""
  benefits:
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  how-it-works:
  - name: "1. Inspire"
    description: Start from scratch, improve an existing design, or have us create you a freash masterpiece.
    background-image: /assets/images/single_page_websites.jpg
  - name: "2. Create"
    description: Let us turn your vision into a reality. Our development process puts pen to paper, and paper to screen.
    background-image: /assets/images/single_page_websites.jpg
  - name: "3. Align"
    description: A chance to make any last minute adjustments or additions to our creation and add the finishing touches.
    background-image: /assets/images/single_page_websites.jpg
  - name: "4. Launch"
    description: The most exciting part of the process, go live time!
    background-image: /assets/images/single_page_websites.jpg

- name: "Consulting: Systems"
  url: /consulting/systems
  background-image: /assets/images/consulting_systems.jpg
  description: Need to implement a new system? Let us guide the installation and rollout.
  icon-image: /assets/images/consulting_systems_icon.png
  tease-line: Business tools, established. 
  shoutouts:
  - name: ""
  - name: ""
  explanations:
  - name: ""
  - name: ""
  - name: ""
  impact-image: /assets/images/digital_solutions_agency.jpg
  quote: ""
  benefits:
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  how-it-works:
  - name: "1. Inspire"
    description: Start from scratch, improve an existing design, or have us create you a freash masterpiece.
    background-image: /assets/images/single_page_websites.jpg
  - name: "2. Create"
    description: Let us turn your vision into a reality. Our development process puts pen to paper, and paper to screen.
    background-image: /assets/images/single_page_websites.jpg
  - name: "3. Align"
    description: A chance to make any last minute adjustments or additions to our creation and add the finishing touches.
    background-image: /assets/images/single_page_websites.jpg
  - name: "4. Launch"
    description: The most exciting part of the process, go live time!
    background-image: /assets/images/single_page_websites.jpg

- name: "Consulting: Operations"
  url: /consulting/operations
  background-image: /assets/images/consulting_operations.jpg
  description: Even the best teams and tools need equally great processes to succeed.
  icon-image: /assets/images/consulting_operations_icon.png
  tease-line: Business processes, solved.
  shoutouts:
  - name: ""
  - name: ""
  explanations:
  - name: ""
  - name: ""
  - name: ""
  impact-image: /assets/images/digital_solutions_agency.jpg
  quote: ""
  benefits:
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  how-it-works:
  - name: "1. Inspire"
    description: Start from scratch, improve an existing design, or have us create you a freash masterpiece.
    background-image: /assets/images/single_page_websites.jpg
  - name: "2. Create"
    description: Let us turn your vision into a reality. Our development process puts pen to paper, and paper to screen.
    background-image: /assets/images/single_page_websites.jpg
  - name: "3. Align"
    description: A chance to make any last minute adjustments or additions to our creation and add the finishing touches.
    background-image: /assets/images/single_page_websites.jpg
  - name: "4. Launch"
    description: The most exciting part of the process, go live time!
    background-image: /assets/images/single_page_websites.jpg

- name: "Consulting: Branding"
  url: /consulting/branding
  background-image: /assets/images/consulting_branding.jpg
  description: Like a makeup team and costume designer for your business.  Make a memorable first impression to your customers.
  icon-image: /assets/images/consulting_branding_icon.png
  tease-line: Your business, dressed to impress.
  shoutouts:
  - name: ""
  - name: ""
  explanations:
  - name: ""
  - name: ""
  - name: ""
  impact-image: /assets/images/digital_solutions_agency.jpg
  quote: ""
  benefits:
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  - name: ""
    description: 
  how-it-works:
  - name: "1. Inspire"
    description: Start from scratch, improve an existing design, or have us create you a freash masterpiece.
    background-image: /assets/images/single_page_websites.jpg
  - name: "2. Create"
    description: Let us turn your vision into a reality. Our development process puts pen to paper, and paper to screen.
    background-image: /assets/images/single_page_websites.jpg
  - name: "3. Align"
    description: A chance to make any last minute adjustments or additions to our creation and add the finishing touches.
    background-image: /assets/images/single_page_websites.jpg
  - name: "4. Launch"
    description: The most exciting part of the process, go live time!
    background-image: /assets/images/single_page_websites.jpg
