- "Single Page Websites"
  name: "Single Page Websites"
  description: Get your business online quickly and easily with one of our single page websites.  Perfect for small businesses and sole traders.
  background-image: /assets/images/single_page_websites.jpg
  url: /websites/single-page-websites